version: '3'

vars:
  KUBECONFIG: ./k3s_kubeconfig.yaml
  SSH_KEY_PATH: ~/.ssh/hetzner_kube_key

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  init:
    desc: "Initialize project with dependency checks and setup wizard"
    cmds:
      - echo "🚀 Initializing kube-hetzner project..."
      - task: check-deps
      - task: setup-keys
      - task: setup-config
      - echo "✅ Initialization complete! Run 'task deploy' to create your cluster."

  check-deps:
    desc: "Verify all required tools are installed"
    cmds:
      - python3 scripts/check_deps.py

  setup-keys:
    desc: "Generate SSH keys if they don't exist"
    status:
      - test -f {{.SSH_KEY_PATH}}
    cmds:
      - echo "🔑 Generating SSH key pair..."
      - ssh-keygen -t rsa -b 4096 -f {{.SSH_KEY_PATH}} -N ""
      - echo "✅ SSH keys generated at {{.SSH_KEY_PATH}}"

  setup-config:
    desc: "Interactive configuration wizard"
    cmds:
      - python3 scripts/setup_config.py

  deploy:
    desc: "Deploy complete Kubernetes cluster with External Secrets"
    deps: [check-config, check-terraform-config]
    cmds:
      - echo "🚀 Starting cluster deployment..."
      - task: terraform-apply
      - task: wait-for-cluster
      - task: wait-for-eso
      - task: apply-secretstores
      - task: apply-letsencrypt
      - echo "🎉 Deployment complete! Run 'task doctor' to verify everything is working."

  check-config:
    desc: "Verify configuration files exist"
    preconditions:
      - test -f terraform.tfvars
      - test -f {{.SSH_KEY_PATH}}
    cmds:
      - echo "✅ Configuration files verified"

  terraform-apply:
    desc: "Apply Terraform configuration"
    cmds:
      - echo "🏗️  Deploying infrastructure with Terraform..."
      - terraform init
      - terraform apply -auto-approve
      - echo "✅ Infrastructure deployed"

  wait-for-cluster:
    desc: "Wait for cluster to be ready"
    cmds:
      - python3 scripts/wait_for_cluster.py

  wait-for-eso:
    desc: "Wait for External Secrets Operator to be ready"
    cmds:
      - echo "⏳ Waiting for External Secrets Operator..."
      - kubectl --kubeconfig={{.KUBECONFIG}} wait --for=condition=ready pod -l app.kubernetes.io/name=external-secrets -n external-secrets --timeout=300s
      - kubectl --kubeconfig={{.KUBECONFIG}} wait --for=condition=ready pod -l app.kubernetes.io/name=bitwarden-sdk-server -n external-secrets --timeout=300s
      - echo "✅ External Secrets Operator is ready"

  apply-secretstores:
    desc: "Apply Bitwarden SecretStore configuration"
    deps: [wait-for-eso]
    cmds:
      - echo "🔐 Applying SecretStore configuration..."
      - kubectl --kubeconfig={{.KUBECONFIG}} apply -f examples/bitwarden-secretstore.yaml
      - python3 scripts/wait_for_secretstores.py

  apply-letsencrypt:
    desc: "Apply Let's Encrypt ClusterIssuer"
    deps: [wait-for-cluster]
    cmds:
      - echo "🔒 Applying Let's Encrypt ClusterIssuer..."
      - kubectl --kubeconfig={{.KUBECONFIG}} apply -f examples/letsencrypt-issuer.yaml
      - echo "✅ Let's Encrypt ClusterIssuer applied"

  apply-examples:
    desc: "Apply example ExternalSecrets (optional)"
    deps: [apply-secretstores]
    cmds:
      - echo "📝 Applying example ExternalSecrets..."
      - kubectl --kubeconfig={{.KUBECONFIG}} apply -f examples/validator-external-secret.yaml
      - echo "✅ Example ExternalSecrets applied"

  doctor:
    desc: "Health check and diagnostic information"
    cmds:
      - python3 scripts/check_cluster_health.py

  logs:
    desc: "Show External Secrets Operator logs"
    cmds:
      - echo "📜 External Secrets Operator logs:"
      - kubectl --kubeconfig={{.KUBECONFIG}} logs -n external-secrets -l app.kubernetes.io/name=external-secrets --tail=50
      - echo ""
      - echo "📜 Bitwarden SDK Server logs:"
      - kubectl --kubeconfig={{.KUBECONFIG}} logs -n external-secrets -l app.kubernetes.io/name=bitwarden-sdk-server --tail=20

  check-terraform-config:
    desc: "Check Terraform configuration and credentials"
    cmds:
      - python3 scripts/check_terraform_config.py

  destroy:
    desc: "Clean teardown of all resources"
    deps: [check-terraform-config]
    prompt: "This will destroy your entire cluster. Are you sure?"
    cmds:
      - echo "🧹 Cleaning up resources..."
      - terraform destroy -auto-approve
      - echo "✅ Cleanup complete"

  reset:
    desc: "Reset configuration (keeps SSH keys)"
    prompt: "This will remove terraform.tfvars and .terraform directory. Continue?"
    cmds:
      - echo "🔄 Resetting configuration..."
      - rm -f terraform.tfvars
      - rm -rf .terraform
      - rm -f terraform.tfstate*
      - rm -f {{.KUBECONFIG}}
      - echo "✅ Configuration reset. Run 'task init' to start over."

  upgrade:
    desc: "Upgrade cluster components"
    cmds:
      - echo "⬆️  Upgrading cluster..."
      - terraform plan
      - terraform apply
      - kubectl --kubeconfig={{.KUBECONFIG}} rollout restart deployment -n external-secrets
      - echo "✅ Upgrade complete"

  backup:
    desc: "Backup important configuration"
    cmds:
      - echo "💾 Creating backup..."
      - mkdir -p backups
      - cp terraform.tfstate backups/terraform.tfstate.$(date +%Y%m%d-%H%M%S) 2>/dev/null || echo "No tfstate to backup"
      - cp {{.KUBECONFIG}} backups/kubeconfig.$(date +%Y%m%d-%H%M%S) 2>/dev/null || echo "No kubeconfig to backup"
      - echo "✅ Backup created in backups/ directory"

  info:
    desc: "Show cluster connection information"
    cmds:
      - echo "📋 Cluster Information:"
      - terraform output
      - echo ""
      - echo "🔗 Connection:"
      - echo "  Kubeconfig {{.KUBECONFIG}}"
      - echo "  SSH Key {{.SSH_KEY_PATH}}"
