# Example BitwardenSecret for developers
# This shows how to create secrets in your application namespace

apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: eas-validator-secrets
  namespace: eas-staging  # Your application namespace
spec:
  organizationId: "b02773e3-a5a8-4c17-92c6-af6a00c2b6cd"
  secretName: eas-validator-secrets  # Name of the Kubernetes secret to create
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    # Map specific Bitwarden secrets to environment variable names
    - bwSecretId: "ffd16da6-9ffa-4888-9738-b33a010c8a74"
      secretKeyName: VALIDATOR_PUBLIC_ADDRESS
    - bwSecretId: "ecacefac-3bec-409e-8ee2-b33a01094c29" 
      secretKeyName: VALIDATOR_PRIVATE_KEY
    # Add more secrets as needed

---
# Example Pod using the BitwardenSecret
apiVersion: v1
kind: Pod
metadata:
  name: eas-validator
  namespace: eas-staging
spec:
  containers:
  - name: validator
    image: your-app:latest
    env:
    # Use secrets as environment variables
    - name: VALIDATOR_PUBLIC_ADDRESS
      valueFrom:
        secretKeyRef:
          name: eas-validator-secrets
          key: VALIDATOR_PUBLIC_ADDRESS
    - name: VALIDATOR_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: eas-validator-secrets
          key: VALIDATOR_PRIVATE_KEY