# Bitwarden ClusterSecretStore for External Secrets Operator
# Apply this AFTER terraform apply completes and ESO is installed

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretstore
spec:
  provider:
    bitwardensecretsmanager:
      organizationID: "b02773e3-a5a8-4c17-92c6-af6a00c2b6cd"
      projectID: "74546659-9867-4647-b7eb-b33a0105a522"
      bitwardenServerSDKURL: "http://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998"
      auth:
        secretRef:
          credentials:
            name: bitwarden-credentials
            key: token
            namespace: external-secrets