# ExternalSecret to pull Cloudflare API token from Bitwarden (Production Project)  
# Alternative configuration that uses production project Bitwarden SecretStore
# Only use if you need a separate cert-manager setup for production environments
# Apply with: kubectl apply -f examples/cloudflare-external-secret-prod.yaml

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-external-secret-prod
  namespace: cert-manager
spec:
  secretStoreRef:
    name: bitwarden-secretstore-prod  # Would need a production SecretStore
    kind: SecretStore
  target:
    name: cloudflare-api-token-secret-prod
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: "b82c2b58-59c1-4000-b9e5-b33f009eaef7"  # API_DNS_PROD_CLOUDFLARE_TOKEN from production project