# ExternalSecret to pull Cloudflare API token from Bitwarden (Staging Project)
# Uses staging project Bitwarden SecretStore to get API_DNS_PROD_CLOUDFLARE_TOKEN
# Apply with: kubectl apply -f examples/cloudflare-external-secret.yaml

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-external-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: bitwarden-secretstore
    kind: SecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: "36eeaa12-a62d-46b4-961c-b33f009e3c74"  # API_DNS_PROD_CLOUDFLARE_TOKEN from staging project