# Example ExternalSecrets for Multi-Tenant Validator Secrets
# This demonstrates how to sync environment-specific secrets from Bitwarden Secrets Manager

# Staging Environment ExternalSecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: validator-secrets
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: SecretStore  # Note: SecretStore, not ClusterSecretStore
  target:
    name: validator-secrets
    creationPolicy: Owner
  data:
  # Staging-specific secrets
  - secretKey: DEPLOY_LOCAL_DEV_VALIDATOR_PUBLIC_ADDRESS
    remoteRef:
      key: "ffd16da6-9ffa-4888-9738-b33a010c8a74"
  - secretKey: DEPLOY_LOCAL_DEV_VALIDATOR_PRIVATE_KEY
    remoteRef:
      key: "ecacefac-3bec-409e-8ee2-b33a01094c29"
  - secretKey: API_STAGING_GITHUB_TOKEN
    remoteRef:
      key: "staging-github-token-uuid"  # Replace with actual staging secret UUID

---
# Production Environment ExternalSecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: validator-secrets
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: SecretStore  # Note: SecretStore, not ClusterSecretStore
  target:
    name: validator-secrets
    creationPolicy: Owner
  data:
  # Production-specific secrets
  - secretKey: DEPLOY_CLOUD_PROD_VALIDATOR_PRIVATE_KEY
    remoteRef:
      key: "57133640-44ba-481f-ba5f-b33a010954ba"
  - secretKey: API_CLOUD_PROD_GITHUB_TOKEN
    remoteRef:
      key: "d958742a-75b7-4e69-8bef-b33a01095c96"
  - secretKey: PROD_DATABASE_PASSWORD
    remoteRef:
      key: "prod-db-password-uuid"  # Replace with actual production secret UUID